OutThereLabs/actix-web-opentelemetry

Cargo.toml
examples/server.rs
src/lib.rs
src/middleware.rs
src/route_formatter.rs

Add route formatter options.
`UuidWildcardFormatter` formats paths from `/users/7bae19f5-8db8-49e6-b3a7-1f3f4ce9a861` -> `/users/*`

Add option for route formatter

---

src/client.rs

From the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-http.md#name):
> Given an RFC 3986 compliant URI of the form scheme:[//host[:port]]path[?query][#fragment], the span name of the span SHOULD be set to the URI path value, unless another value that represents the identity of the request and has a lower cardinality can be identified (e.g. the route for server spans; see below).

Make client span name match otel spec

---

Cargo.toml
examples/client.rs
src/client.rs
src/lib.rs
src/middleware/trace.rs

1. Simplify client tracing
Previous:
```rust
let mut response = actix_web_opentelemetry::with_tracing(
client.get("http://localhost:8080/users/103240ba-3d8d-4695-a176-e19cbc627483?a=1"),
|request| request.send(),
)
.await
```
New:
```rust
let mut response = client
.get("http://localhost:8080/users/103240ba-3d8d-4695-a176-e19cbc627483?a=1")
.trace_request()
.send()
.await
```
2. Use global propagator API for server tracing to avoid need to specify propagator.

Simplify client tracing and use global propagator API

---

examples/server.rs
src/client.rs
src/lib.rs
src/middleware/metrics.rs
src/middleware/route_formatter.rs
src/middleware/trace.rs

Custom format now can be added via:
```rust
HttpServer::new(|| {
let id_formatter = RegexFormatter::new(r"\d+", ":id").unwrap();
App::new()
.wrap(RequestTracing::with_formatter(id_formatter)
.service(web::resource("/").to(index))
})
.bind("127.0.0.1:8080")?
.run()
.await
```

Allow specifying route format with custom regex

---

Cargo.toml
examples/client.rs
examples/server.rs
src/lib.rs
src/middleware/metrics.rs
src/middleware/route_formatter.rs
src/middleware/trace.rs

* Switch to new Actix 3 route extraction via [match_pattern](https://docs.rs/actix-web/3/actix_web/struct.HttpRequest.html#method.match_pattern).
* Remove old route formatters that were workarounds for missing match pattern method above.
* `RouteFormatter` trait can still be used to adjust the default match pattern output as it is not run on the resulting output pattern.
Resolves #24

Upgrade actix-web to version 3

---

.github/workflows/ci.yaml
Cargo.toml
examples/client.rs
examples/server.rs
src/client.rs
src/lib.rs
src/middleware/metrics.rs
src/middleware/mod.rs
src/middleware/trace.rs

* Move request metrics behind `metrics` feature as it is still unstable in OpenTelemetry
* Remove default features from `actix-web` and `actix-http` dependencies
* Upgrade to `opentelemetry` 0.9.x
* Simplify docs and examples to use new trace/metrics pipelines
* Use `opentelemetry-semantic-conventions` for server and client key names
* Remove deprecated `actix_web_opentelemetry::with_tracing` function.
* Change default route name from `unmatched` to `default`
Resolves #27

Update opentelemetry to 0.9.x

---

Cargo.toml
README.md
examples/client.rs
examples/server.rs
src/lib.rs

Opentelemetry v0.12 supports tokio 1.0 which actix web 3.x does not support. Support for latest otel is added here by manually creating a tokio 0.2.x compatible batch span exporter in the examples.

Update to opentelemetry v0.12.x

---

CHANGELOG.md
Cargo.toml

Note: optentelemetry `v0.12.x` uses tokio 1.0. See the [updated examples](https://github.com/OutThereLabs/actix-web-opentelemetry/blob/e29c77312d6a906571286f78cc26ca72cf3a0b6f/examples/server.rs#L17-L40) for compatible setup until actix-web supports tokio 1.0.
- Update to OpenTelemetry v0.12.x #48

Prepare for v0.10.0 release

---

Cargo.toml
README.md
examples/client.rs
examples/server.rs
src/lib.rs

Now that we have tokio 1 support, re-enable the `tokio` feature in in jaeger for async exporting

Re-add jaeger tokio dependency

---

Cargo.toml
examples/client.rs
src/client.rs
src/lib.rs

actix-web is not re-exporting awc's client module anymore, since
https://github.com/actix/actix-web/commit/871ca5e4ae2bdc22d1ea02701c2992fa8d04aed7
and is  documented here
https://github.com/actix/actix-web/blob/22dcc311937967b9da972b6304cb97d5684d2cae/CHANGES.md
Note that even if the change is on the unreleased section, this change
was released on actix-web = "4.0.0-beta.4".

Upgrade to latest actix-web beta releases

---

Cargo.toml
README.md
src/middleware/trace.rs

I'm making a clean PR from #59 
Add support for tracing sync (or the sync part of) middlwares in a single trace. This is behind a feature flag since it adds some overhead. I added docs for the `metrics` flag as well, just so all flags are documented. Let me know if anything seems off.

Support tracing sync middlewares

---

src/middleware/metrics.rs
src/util.rs

This will avoid a separate bucket for each useragent

Use proper metrics values, not trace values

---

src/client.rs

Reduces the default client span name to method and host, e.g. `GET www.google.com`

Reduce default span namer cardinality

---

CHANGELOG.md
Cargo.toml
examples/server.rs
src/client.rs
src/lib.rs
src/middleware/metrics.rs
src/util.rs

I didn't see a great CHANGELOG for the sem cov changes but found the suggested replacements in the Java code:
https://github.com/open-telemetry/opentelemetry-java/blob/7b8608591e1737ea0727d2373ddd813bc18cdaaa/semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java#L2008
HTTP_HOST -> NET_HOST_NAME
HTTP_SERVER_NAME -> NET_HOST_NAME
NET_PEER_IP -> NET_SOCK_PEER_ADDR

Update to otel v0.19

---

src/middleware/metrics.rs

This will result in promethus names like `http_server_active_requests_{request}` currently due to an upstream bug.

Remove active request units until bug is resolved

---

src/middleware/metrics.rs

Noticed that this seemed to be wrong. Probably just a copy-paste typo:

Fix typo for http_server_response_size metric

---

Cargo.toml
examples/client.rs
examples/server.rs
src/client.rs
src/middleware/trace.rs
src/util.rs

Update to otel v0.23 and switch to `opentelemetry-otlp` as `opentelemetry-jaeger` is now deprecated.

Update to otel v0.23

---

Cargo.toml
src/client.rs
src/middleware/metrics.rs
src/util.rs

Could not fully upgrade to 0.25 because of `opentelemetry-prometheus` not being up-to-date but this is the next best thing.

Update opentelemetry packages to 0.24

---

src/lib.rs
src/middleware/metrics.rs
src/util.rs

Adding a builder method `with_metric_attrs_from_req` that accepts a function to generate metric attributes from the request. Function has the same signature with and by default is `util::metrics_attributes_from_request`. Also exposing `metrics_attributes_from_request` since whoever wants to add additional attributes may want to reuse it and extend its result.
Fixes #171

add RequestMetricsBuilder.with_metric_attrs_from_req

---

examples/server.rs

I found that the updated example for otel 0.27.0 wasn't sending my traces (to honeycomb in my case). Ensuring that the trace provider is 'set' or registered seemed to fix the problem and matches the instructions here:
https://opentelemetry.io/docs/languages/rust/getting-started/#instrumentation

fix: register the tracer provider in server example
